source "https://rubygems.org"

gem 'activesupport-inflector'
gem 'addressable'
gem 'anybase'
gem 'excon'
gem 'httparty'
gem 'i18n'
gem 'multi_json'
gem 'redis'
gem 'rest-client'
gem 'resque'
gem 'resque-scheduler'
gem 'rufus-scheduler'
gem 'typhoeus'
gem 'virtus'